    
import os
FC=os.environ.get('FC')
CC=os.environ.get('CC')
csources=['./sysdep/yylinux.c']

envC=Environment(CC=CC)
if csources:
    envC.Library('yylinuxc',csources)

fsources = [
'admin/ahist.f95',  'admin/apcon.f95',  'admin/aquit.f95',  'admin/asets.f95', 'admin/asetc.f95', 'admin/astup.f95',  'admin/atime.f95','admin/astep.f95',  
'./util/ucloc.f95','./util/ufftp.f95','./util/umtlu.f95','./util/usphe.f95','./util/uspst.f95',
'./dynamics/dsetv.f95','./proj/tintgr/dhydr.f95','./dynamics/dsphe.f95','./dynamics/ddiag.f95','./dynamics/dmfix.f95','./dynamics/dmtrx.f95','./dynamics/dsetc.f95','./dynamics/dvect.f95','./dynamics/ddifc.f95','./dynamics/dvtmp.f95',  './physics/pmisc.f95','./physics/pshl0.f95','./physics/pvdfy.f95', 
'./proj/tintgr/dgdyn-2.f95','./proj/tintgr/dsetd-2.f95','./proj/tintgr/dintg-2.f95','./proj/tintgr/dadvn-2.f95','./proj/tintgr/dstep-2.f95','./proj/tintgr/dterm-2.f95','./proj/tintgr/astrt-2.f95','./proj/tintgr/auser-2.f95','./proj/tintgr/dadmn-2.f95','./proj/tintgr/dbulk.f95','./proj/tintgr/aadmn-2.f95',
'./atmmain.f95'
]
f77sources = [
'./io/iavrg.f','./io/icord.f','./io/idiag.f','./io/ifopn.f','./io/igtio.f','./io/igzio.f','./io/ihist.f','./io/ihsub.f','./io/irdat.f','./io/irwgd.f','./io/is2po.f','./io/istrt.f',
'./sysdep/ylinux.f', './util/ucaln.f','./util/usubs.f',
# './admin/ahist.f','./admin/apcon.f','./admin/aquit.f','./admin/asetc.f','./admin/asets.f','./admin/astep.f','./admin/astup.f','./admin/atime.f'        
] 

# For OpenMP
#LDFLAGS= ['-fopenmp','-Wl,-stack_size,0x40000000']
#FFLAGS  = ['-O2', '-m64', '-Wall', '-fconvert=big-endian','-fopenmp','-pthread']

LDFLAGS= []
#FFLAGS  = ['-O2','-floop-parallelize-all','-ftree-parallelize-loops=8', '-m64', '-Wall', '-fconvert=big-endian','-fopenmp','-pthread']
FFLAGS_F77  = ['-Ofast', '-m64', '-Wall','-fconvert=big-endian']
FFLAGS_F95  = ['-Ofast', '-m64', '-Wall','-Wno-unused','-Wno-unused-dummy-argument','-fimplicit-none','-fcheck=bounds','-ffree-form', '-ffree-line-length-none','-fconvert=big-endian']

envF77=Environment(FORTRAN=FC,LINK=FC,LINKFLAGS=LDFLAGS,FORTRANFLAGS=FFLAGS_F77,FORTRANPATH=['.','..','/opt/local/include','/usr/local/include'])
# NOTE: F95PATH is essential for module support, FORTRANPATH does NOT work!
envF95=Environment(F95=FC,LINK=FC,LINKFLAGS=LDFLAGS,F95FLAGS=FFLAGS_F95,F95PATH=['.','..','/opt/local/include','/usr/local/include'])
#envF=Environment(FORTRAN=FC,F95=FC,LINK=FC,LINKFLAGS=LDFLAGS,F95FLAGS=FFLAGS_F95,F77FLAGS=FFLAGS_F77,FORTRANPATH=['.','..','/opt/local/include','/usr/local/include'])

envF77.Library('f77lib',f77sources)
envF95.Program('atmmain',fsources,LIBS=['f77lib','yylinuxc','m','c'],LIBPATH=['.','/opt/local/lib','/usr/local/lib'])
