import os
FC=os.environ.get('FC')

fsources = [
'addabc.f',
'addcon.f',
'averag.f',
'bahr.f',
#'commons.f',
'params_commons.f',
'contoc.f',
'diagnos.f',
'fluxoc.f',
'gridos.f',
'hovout.f',
'intfsum.f',
'iocean.f',
'maxims.f',
'multip.f',
'ninout.f',
'ofield.f',
'parames.f',
'patch.f',
'rangau.f',
'restax.f',
'select.f',
'setval.f',
'shallow.f',
'slvout.f',
'ssteqs.f',
'sstout.f',
'starts.f',
'stoatm.f',
'stress.f',
'yemoda.f'
]

# For OpenMP
#LDFLAGS= ['-fopenmp','-Wl,-stack_size,0x40000000']
#FFLAGS  = ['-O2', '-m64', '-Wall', '-fconvert=big-endian','-fopenmp','-pthread']

LDFLAGS= []
#FFLAGS_F77  = ['-O3', '-m64', '-Wall','-Wno-unused','-Wno-unused-dummy-argument','-ffree-form', '-ffree-line-length-none','-fconvert=big-endian']
FFLAGS_F77  = ['-Ofast', '-m64', '-Wall'] # THIS IS WRONG: '-fconvert=big-endian']

# NOTE: F77PATH is essential for module support, FORTRANPATH does NOT work!
#envF77=Environment(F77=FC,LINK=FC,LINKFLAGS=LDFLAGS,F77FLAGS=FFLAGS_F77,F77PATH=['.','..','/opt/local/include','/usr/local/include'])
envF77=Environment(FORTRAN=FC,LINK=FC,LINKFLAGS=LDFLAGS,FORTRANFLAGS=FFLAGS_F77,FORTRANPATH=['.','..','/opt/local/include','/usr/local/include'])

envF77.Program('Shallow',fsources,LIBS=[],LIBPATH=['.','/opt/local/lib','/usr/local/lib'])


