// Wrapper for GMCF generated by $0 on $date. Only parameter is $nmodels
#include "SBA/Types.h"
#include "SBA/System.h"
#include "SBA/Tile.h"

class GMCF {
    public:
		int64_t atmosphere_gmcf(SBA::System* sba_sysptr, SBA::Tile* sba_tileptr, uint64_t);
		int64_t ocean_gmcf(SBA::System* sba_sysptr, SBA::Tile* sba_tileptr, uint64_t);

};
